python:
  # part of a zip_keys: python, python_impl, numpy
  - 3.9.* *_cpython
  - 3.10.* *_cpython
  - 3.11.* *_cpython
python_impl:
  # part of a zip_keys: python, python_impl, numpy
  - cpython
  - cpython
  - cpython
numpy:
  - >1.25.0
  - >1.25.0
  - >1.25.0
