{% set name = "MDAnalysis" %}
{% set version = "2.5.0" %}
{% set sha256 = "06ce4efab6ca1dbd2ee2959fc668049e1d574a8fe94ab948a4608244da1d016b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 2
  skip: true  # [python_impl == 'pypy']
  skip: true  # [py>311]
  skip: true  # [py<39]
  script:
    - ${CXX} --version
    - {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - numpy {{ numpy }}
    - cython
    - packaging

  run:
    - python
    - scipy >=1.5.0
    - {{ pin_compatible('numpy', lower_bound='1.21') }}
    - matplotlib-base >=1.5.1
    - seaborn
    - netcdf4 >=1.0
    - biopython >=1.80
    - networkx >=2.0
    - griddataformats >=0.4.0
    - joblib >=0.12
    - gsd >=1.9.3,<3.0.0
    - mmtf-python >=1.0.0
    - scikit-learn
    - tidynamics >=1.0.0
    - tqdm >=4.43.0
    - threadpoolctl
    - fasteners
    - packaging
    - h5py >=2.10.0
    - pytng >=0.2.3
    - pyedr >=0.7.1

test:
  imports:
    - MDAnalysis
    - MDAnalysis.analysis
    - MDAnalysis.lib.c_distances_openmp
    - MDAnalysis.lib.c_distances
  requires:
    - pip
    - pytest
    - pytest-xdist
    - mdanalysistests
  commands:
    - $CXX --version
    - pytest -v -n auto --pyargs MDAnalysisTests

about:
  home: https://www.mdanalysis.org
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: A Python package for the handling and analysis of molecular simulations data.
  description: |
    MDAnalysis is a Python library to analyze trajectories from molecular
    dynamics (MD) simulations. It can read and write most popular formats, and
    provides a flexible and fast framework for writing custom analysis through
    making the underlying data easily available as NumPy arrays.
  doc_url: https://docs.mdanalysis.org/
  dev_url: https://github.com/MDAnalysis/mdanalysis

extra:
  recipe-maintainers:
    - kain88-de
    - orbeckst
    - richardjgowers
    - ialibay
