{% set name = "MDAnalysis" %}
{% set version = "2.8.0" %}
{% set sha256 = "0cf8efda7cb4a1cc33a92d2cd0d69a3d9b33c06c603df3c386caf6edccf46099" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/m/mdanalysis/mdanalysis-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [python_impl == 'pypy']
  skip: true  # [py>313]
  skip: true  # [py<310]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - numpy {{ numpy }}
    - cython
    - packaging
    - setuptools
  run:
    - python
    - scipy >=1.5.0
    - numpy >=1.23.2
    - matplotlib-base >=1.5.1
    - seaborn    # [not ppc64le]
    - netcdf4 >=1.0
    - biopython >=1.80  # [not py>312]
    - networkx >=2.0
    - griddataformats >=0.4.0
    - joblib >=0.12
    - gsd >3.0.0
    - mmtf-python >=1.0.0
    - scikit-learn
    - tidynamics >=1.0.0
    - tqdm >=4.43.0
    - threadpoolctl
    - fasteners
    - packaging
    - h5py >=2.10.0
    - pytng >=0.2.3    # [not ppc64le]
    - pyedr >=0.7.1
    - mda-xdrlib
    - waterdynamics >=1.2.0
    - pathsimanalysis >=1.2.0
    - mdahole2-base >=0.5.0

test:
  imports:
    - MDAnalysis
    - MDAnalysis.analysis
    - MDAnalysis.lib.c_distances_openmp
    - MDAnalysis.lib.c_distances

about:
  home: https://www.mdanalysis.org
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: LICENSE
  summary: A Python package for the handling and analysis of molecular simulations data.
  description: |
    MDAnalysis is a Python library to analyze trajectories from molecular
    dynamics (MD) simulations. It can read and write most popular formats, and
    provides a flexible and fast framework for writing custom analysis through
    making the underlying data easily available as NumPy arrays.
  doc_url: https://docs.mdanalysis.org/
  dev_url: https://github.com/MDAnalysis/mdanalysis

extra:
  recipe-maintainers:
    - hmacdope
    - kain88-de
    - orbeckst
    - richardjgowers
    - ialibay
