{% set name = "MDAnalysis" %}
{% set version = "2.7.0" %}
{% set sha256 = "572e82945e5d058e3749ec5f18e6b3831ef7f2119cb54672567ae9a977201e93" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/hmacdope/mdanalysis.git
  git_rev: clang_compiler_error


build:
  number: 1
  skip: true  # [python_impl == 'pypy']
  skip: true  # [py>312]
  skip: true  # [py<39]
  script: cd package && {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - numpy {{ numpy }}
    - cython
    - packaging

  run:
    - python
    - scipy >=1.5.0
    - {{ pin_compatible('numpy', lower_bound='1.22.3') }}
    - matplotlib-base >=1.5.1
    - seaborn    # [not ppc64le]
    - netcdf4 >=1.0
    - biopython >=1.80
    - networkx >=2.0
    - griddataformats >=0.4.0
    - joblib >=0.12
    - gsd >3.0.0
    - mmtf-python >=1.0.0
    - scikit-learn
    - tidynamics >=1.0.0
    - tqdm >=4.43.0
    - threadpoolctl
    - fasteners
    - packaging
    - h5py >=2.10.0
    - pytng >=0.2.3    # [not ppc64le]
    - pyedr >=0.7.1
    - mda-xdrlib

test:
  imports:
    - MDAnalysis
    - MDAnalysis.analysis
    - MDAnalysis.lib.c_distances_openmp
    - MDAnalysis.lib.c_distances

about:
  home: https://www.mdanalysis.org
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: A Python package for the handling and analysis of molecular simulations data.
  description: |
    MDAnalysis is a Python library to analyze trajectories from molecular
    dynamics (MD) simulations. It can read and write most popular formats, and
    provides a flexible and fast framework for writing custom analysis through
    making the underlying data easily available as NumPy arrays.
  doc_url: https://docs.mdanalysis.org/
  dev_url: https://github.com/MDAnalysis/mdanalysis

extra:
  recipe-maintainers:
    - kain88-de
    - orbeckst
    - richardjgowers
    - ialibay
