{% set name = "MDAnalysis" %}
{% set version = "2.4.1" %}
{% set sha256 = "6c960741b22bb8ab3994c011629c64df56ce1f5cef748adc02fb03f3909b727e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  skip: true  # [python_impl == 'pypy']
  skip: true  # [py>311]
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - numpy {{ numpy }}
    - cython
    - packaging

  run:
    - python
    - scipy >=1.5.0
    - {{ pin_compatible('numpy', lower_bound='1.20', upper_bound='1.23') }}
    - matplotlib-base >=1.5.1
    - seaborn
    - netcdf4 >=1.0
    - biopython >=1.80
    - networkx >=2.0
    - griddataformats >=0.4.0
    - joblib >=0.12
    - gsd >=1.9.3
    - mmtf-python >=1.0.0
    - scikit-learn
    - tidynamics >=1.0.0
    - tqdm >=4.43.0
    - threadpoolctl
    - fasteners
    - packaging
    - h5py >=2.10.0
    - pytng >=0.2.3

test:
  imports:
    - MDAnalysis
    - MDAnalysis.analysis
    - MDAnalysis.lib.c_distances_openmp
    - MDAnalysis.lib.c_distances

about:
  home: https://www.mdanalysis.org
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: A Python package for the handling and analysis of molecular simulations data.
  description: |
    MDAnalysis is a Python library to analyze trajectories from molecular
    dynamics (MD) simulations. It can read and write most popular formats, and
    provides a flexible and fast framework for writing custom analysis through
    making the underlying data easily available as NumPy arrays.
  doc_url: https://docs.mdanalysis.org/
  dev_url: https://github.com/MDAnalysis/mdanalysis

extra:
  recipe-maintainers:
    - kain88-de
    - orbeckst
    - richardjgowers
    - ialibay
