{% set name = "MDAnalysis" %}
{% set version = "1.0.1" %}
{% set sha256 = "dc2cf34391b5eb1733fca1ab14e0de2e381d2d595c95923403f42cb2e39c9dad" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 2
  skip: true  # [win]
  skip: true  # [python_impl == 'pypy']
  skip: true  # [py>38]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - numpy >=1.13.3,<1.17
    - cython

  run:
    - python
    - scipy
    - numpy >1.13.3,<1.17
    - matplotlib-base
    - seaborn
    - netcdf4
    - biopython
    - networkx >=1.0
    - griddataformats >=0.4.0
    - joblib >=0.12
    - gsd  # [not win]
    - mmtf-python >=1.0
    - scikit-learn
    - tqdm >=4.43

test:
  imports:
    - MDAnalysis
    - MDAnalysis.analysis
    - MDAnalysis.lib.c_distances_openmp
    - MDAnalysis.lib.c_distances

about:
  home: https://www.mdanalysis.org
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: An object-oriented library to analyze molecular dynamics trajectories generated by CHARMM, Gromacs, NAMD, LAMMPS, or Amber.
  description: |
    MDAnalysis is a Python library to analyze trajectories from molecular
    dynamics (MD) simulations. It can read and write most popular formats, and
    provides a flexible and fast framework for writing custom analysis through
    making the underlying data easily available as NumPy arrays.
  doc_url: https://www.mdanalysis.org/docs/
  dev_url: https://github.com/MDAnalysis/mdanalysis

extra:
  recipe-maintainers:
    - kain88-de
    - orbeckst
    - richardjgowers
    - ialibay
