{% set name = "MDAnalysis" %}
{% set version = "2.0.0" %}
{% set sha256 = "aa3079d1a82305eba58cf567fac8fc231940184ed88f9a4451be8433f4a06d3e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [python_impl == 'pypy']
  skip: true  # [py>39]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - numpy >=1.16.0
    - cython

  run:
    - python
    - scipy >=1.0.0
    - numpy >1.16.0
    - matplotlib-base >=1.5.1
    - seaborn
    - netcdf4 >=1.0
    - biopython >=1.71
    - networkx >=1.0
    - griddataformats >=0.4.0
    - joblib >=0.12
    - gsd >=1.9.3  # [win]
    - gsd >=1.4.0  # [not win]
    - mmtf-python >=1.0.0
    - scikit-learn
    - tqdm >=4.43.0
    - threadpoolctl

test:
  imports:
    - MDAnalysis
    - MDAnalysis.analysis
    - MDAnalysis.lib.c_distances_openmp
    - MDAnalysis.lib.c_distances

about:
  home: https://www.mdanalysis.org
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: An object-oriented library to analyze molecular dynamics trajectories generated by CHARMM, Gromacs, NAMD, LAMMPS, or Amber.
  description: |
    MDAnalysis is a Python library to analyze trajectories from molecular
    dynamics (MD) simulations. It can read and write most popular formats, and
    provides a flexible and fast framework for writing custom analysis through
    making the underlying data easily available as NumPy arrays.
  doc_url: https://www.mdanalysis.org/docs/
  dev_url: https://github.com/MDAnalysis/mdanalysis

extra:
  recipe-maintainers:
    - kain88-de
    - orbeckst
    - richardjgowers
    - ialibay
